apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: secrets-manager-readonly
  namespace: default
spec:
  providerConfigRef:
    name: default
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "ec2.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
    inlinePolicy:
      - name: SecretsManagerReadOnly
        policy: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "secretsmanager:GetSecretValue",
                  "secretsmanager:DescribeSecret",
                  "secretsmanager:ListSecrets",
                  "secretsmanager:ListSecretVersionIds"
                ],
                "Resource": "*"
              }
            ]
          }